<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Course;
use Faker\Generator as Faker;

$factory->define(Course::class, function (Faker $faker) {
    return [
        //
        'course_name' => $faker->unique()->randomElement([
            'Introduction to Interactive Programming in Python - Part 1',
            'C#',
            'HTML5',
            'COBOL',
            'FOTRAN',
            'CSS3',
            'Extinctions: Past and Present',
            'Understanding Dementia',
            'Six Sigma: Define and Measure',
            'Maintaining a Mindful life',
            'Understanding Multiple',
            'Learning How To Learn for Youth',
            'A life of Happiness and Fullfillment',
            'Introduction to Real-Time Audio Programming in Chuck',
            'Justice',
            'Matrix Algebra for Engineers',
            'Elements of AI',
            'Presentation Skills',
            'Start Taking with 1.3 Billion People',
            'Fibonacci Numbers and the Golden Ratio',
            'Introduction to Programming with MATLAB',
            'Introduction to Dutch',
            'What is a Mind?',
            'Machine Learning for Muscians and Arts',
            'Introduction to Dynamical System and Chaos',
            'Understanding Clinical Research: Behind the Statistics',
            'Umano Digitale',
            'Mindfulness for Wellbeing and Peak Performance',
            'Startup School',
            'English in Early Childhood: Language and Learning Development',
            'English for the Workplace',
            'Discover Dentistry',
            'Medical Neuroscience',
            'Forensic Facial',
            'Machine Learning',
            'Basic Spanish 2: One Step Further',
            'EU Policy and implementation: making Europe work!',
            'Mechanics of Materials I: Fundamentals of Stress & Strain and Axial Loading',
            'Learn to Program: The Fundamentals',
            'Mathematical Economics',
            'Critical Thinking at University: An Introduction',
            'Cartography',
            'Dino 101: Dinosaur Paleobiology',
            'Computing in Python 1: Fundamentals and Procedural Programming',
            'Shakespeare Matters',
            'Divide and Conquer, Sorting and Searching, and Randomized Algorithms',
            'Introduction to Engineering Mechanics',
            'Introduction to Biology - The Secret of Life',
            'Model Thinking',
            'Literature of the English Country House',
            'AP Microeconomics',
            'Digital Marketing Course For Working Professionals',
            'How to Succeed at: Writing Applications',
            'Preparing to Manage Human Resources',
            'Creative Applications of Deep Learning with Tensorflow',
            'Education for All: Disability, Diversity and inclusion',
            'The Science of Everyday Thinking',
            'Marketing in a Digital World',
            'Gender and Sexuality: Applications in Society',
            'The Analytics Edge',
            'Cryptography I',
            'Social Psychology',
            'Deep Learning in Python',
            'Moralities of Everyday Life',
            'Marketing Digital: Content & Community Manager',
            'Astrobiology and the Search for Extraterrestrial Life',
            'Functional Programming Principles in Scala',
            'Circuits and Electronics 1: Basic Circuit Analysis',
            'Internet History, Technology, and Security',
            '9 Months, Online Machine Learning & AI Diploma',
            'Food as Medicine',
            'Introduction to Genetics and Evolution',
            'Introduction to Financial Accounting',
            'Critical Perspectives on Management',
            'Gamification',
            'Vital Signs: Understanding What the Body is Telling Us',
            'Understanding the GDPR',
            'The Ancient Greeks',
            'The Science of Happiness',
            'How to Use Git and GitHub',
            'Buddhism and Modern Psychology'
        ]),
        'course_code' => $faker->unique()->numberBetween(1, 80),
        'unit' => $faker->randomElement(array(0, 2, 3, 4)),
        'text' => $faker->text,
    ];
});
